### ISSUE TITLE
The full arguments using dmd to compile a single example/program with the already build DWT libs

### ISSUE THREAD

**Issue by LukyGuyLucky** [d-widget-toolkit/dwt#127]
Greetings,

After successfully built the DWT libraries via dub,yes I can compile all the samples in the dwt package.However it seems that when comiling examples by using dub --single tools/build_snippets.d ,the libraries had to compile again and again .So I want to compile examples with dmd  -Ldwt.lib -Ldwt_base.lib -bla -bla ....But unfortunately I failed.

May I ask what's the full compiling command to build a single example with dmd+ dwt.lib + dwt_base.lib?

Thank you in advance.

**Comment by jacob-carlborg** [comment]
> So I want to compile examples with dmd -Ldwt.lib -Ldwt_base.lib -bla -bla ....But unfortunately I failed.

What command did you try? Do you get any errors?

> May I ask what's the full compiling command to build a single example with dmd+ dwt.lib + dwt_base.lib?

For Windows you need to link with the following system libraries:

https://github.com/d-widget-toolkit/dwt/blob/db73d794144f5652fa8ff96131757828cb34f84c/dub.sdl#L48-L61

For Ubuntu you need to link with system libraries below. For other Linux distributions you would need to link with similar libraries but the names might differ.

https://github.com/d-widget-toolkit/dwt/blob/db73d794144f5652fa8ff96131757828cb34f84c/dub.sdl#L94-L118

**Comment by LukyGuyLucky** [comment]
Thanks a lot for the reply.
