### ISSUE TITLE
Range violation

### ISSUE THREAD

**Issue by sentenzo** [d-widget-toolkit/dwt#24]
I've got [one ugly application](https://gist.github.com/sentenzo/ced3ef0b3058bf11261ef8d4c137cb4a) with *TableTree Widget* on **Linux** with **DMD64 D Compiler v2.072.0**, and it runs pretty well. But at the moment of disposing (when `display.dispose()` command executes) it fails with an error:

    core.exception.RangeError@org/eclipse/swt/custom/TableTreeItem.d(575): Range violation
    ----------------
    ??:? _d_arraybounds [0xbac987]
    ??:? org.eclipse.swt.custom.TableTreeItem.__array [0x9c8d34]
    ...

I guess, the reason is in incorrect auto-typing in this cycle:

    // dwt/org.eclipse.swt.gtk.linux.x86/src/org/eclipse/swt/custom/TableTreeItem.d
    ....
    for (auto i = items.length - 1; i >= 0; i--) { // row 575
    ...

So, `i` becomes of type `size_t` which is unsigned. 

It's easy to fix [all such bugs](https://github.com/d-widget-toolkit/org.eclipse.swt.gtk.linux.x86/search?utf8=%E2%9C%93&q=%22auto+i+%3D+items.length%22&type=Code) in one pull request, but I found your [**jport** repository](https://github.com/d-widget-toolkit/jport), so I thought, maybe it is more like kind of **jport** issue. I don't have Scala-skills to say for sure.

**Comment by jacob-carlborg** [comment]
JPort is not finished yet, so it's not being used. The existing code ported by hand.

**Comment by jacob-carlborg** [comment]
Please let me know if the fix worked for you.

**Comment by sentenzo** [comment]
Yes, it completely fixes described issue in my case.
