### ISSUE TITLE
Cannot compile snippets

### ISSUE THREAD

**Issue by nicesai** [d-widget-toolkit/dwt#31]
I got several errors from "C:\dwt-master\imp\org\eclipse\swt\ole\win32\OleClientSite.di", on opening it I see several syntax errors, probably error in automated translation?

I removed that imp\org folder and added C:\dwt-master\org.eclipse.swt.win32.win32.x86\src to the sc.ini file then all the snippets compiled without error. 

Could you please fix this?

**Comment by jacob-carlborg** [comment]
It's due to a bug in the compiler. It's been recently fixed and should be part of the next release of DMD.
