### ISSUE TITLE
Build fails utilizing LDC 1.8.0

### ISSUE THREAD

**Issue by JesseKPhillips** [d-widget-toolkit/dwt#35]
The multiple declarations of Windows functions appear to have a negative affect on the LDC compiler.

%AppData%\Roaming\dub\packages\dwt-1.0.0_swt-3.4.1\dwt\org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINAPI.d(2302,21): Error: Function type does not match previously declared function with the same mangled name: SendMessageW

If I remove the duplicate definitions then we run into type conversion issues everywhere.

**Comment by jacob-carlborg** [comment]
LDC is currently not supported.

**Comment by JesseKPhillips** [comment]
Well, it looks like this will be a bigger problem with DMD 2.079. I get a number of errors from WINTYPES.

%AppData%\Local\dub\packages\dwt-1.0.0_swt-3.4.1\dwt\org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15493,10): Error: function org.eclipse.swt.internal.win32.WINTYPES.SCRIPT_LOGATTR.fWordStop(uint val) cannot be overloaded with another extern(Windows) function at ..\..\..\..\AppData\Local\dub\packages\dwt-1.0.0_swt-3.4.1\dwt\org.eclipse.swt.win32.win32.x86\src\org\eclipse\swt\internal\win32\WINTYPES.d(15486,10)

**Comment by jacob-carlborg** [comment]
Yeah, I think it's this one: https://issues.dlang.org/show_bug.cgi?id=18385.

**Comment by JesseKPhillips** [comment]
It seems like the issue is going to stay around. Does that mean all of the calls onto these methods are going to need to change so they are accepted by the one true definition?

**Comment by jacob-carlborg** [comment]
> It seems like the issue is going to stay around.

Well, I hope they fix it, it's a pretty big regression.

> Does that mean all of the calls onto these methods are going to need to change so they are accepted by the one true definition?

Actually, looking at this specific error, the methods can actually be `extern(D)`, which would solve the problem.

**Comment by kntroh** [comment]
I overlooked this Issue. I think will be resolved it by Pull Request #52.
