### ISSUE TITLE
Build of the main.d fails

### ISSUE THREAD

**Issue by schlupa** [d-widget-toolkit/dwt#36]
All I get is:
Invalid SemVer format:  1.0.0

What does that mean? Where the documentation?  
What is it with this main.d anyway? What's its purpose, is it an example to test if dub did its work or what? What does I have to do to add dwt in my app, which doesn't use dub?
How do I set up the stuff if I want to build an app in 32 bit and another in 64 bits etc..

**Comment by trikko** [comment]
Probably you pasted the code from example, where there's an extra whitespace after "~>"

> dependency "dwt" version="~> 1.0.0"

instead of:

> dependency "dwt" version="~>1.0.0"

**Comment by schlupa** [comment]
Ok, that was the issue with this specific error. I close this issue but open a new one because I don't get anything built, neither on windows nor on Linux.
