### ISSUE TITLE
A handles of Condition continue to increase until the GC works.

### ISSUE THREAD

**Issue by kntroh** [d-widget-toolkit/dwt#49]
Running this application in a Windows will increase semaphore handles limitless.

    import org.eclipse.swt.all;
    import java.lang.all;

    import core.thread;
    import std.conv;

    void main() {
        auto display = new Display();
        auto shell = new Shell();

        auto runnable = new class Runnable {
            int i = 0;
            override void run() {
                if (!shell.isDisposed()) shell.setText(i.text);
                i++;
            }
        };
        auto thr = new core.thread.Thread({
            while (!shell.isDisposed()) {
                // If enabled this line, Handles doesn't increased.
                //import core.memory; core.memory.GC.collect();
                display.asyncExec(runnable);
                core.thread.Thread.sleep(dur!"msecs"(10));
            }
        });
        thr.start();

        shell.open();
        while (!shell.isDisposed()) {
            if (!display.readAndDispatch()) {
                display.sleep();
            }
        }
    }

The `java.nonstandard.sync.condition.Condition`(based on `core.sync.condition`) release a semaphore handle in destructor, But A destructor will not run until the GC works. Since the starting condition of the GC is memory usage, the GC doesn't work even if number of handles increases.

I have modified the code of DWT to work around this problem, But I'm not sure this is the best way.

 * https://github.com/kntroh/dwt/commit/7011b5bf35aa90695bd0915c781fc46249009ba9

If this is better than doing nothing, I'll send a pull request.

**Comment by kntroh** [comment]
Maybe DWT-linux has a same problem.

**Comment by jacob-carlborg** [comment]
> If this is better than doing nothing, I'll send a pull request.

I don't have any other ideas.

> Maybe DWT-linux has a same problem.

I would guess so.

**Comment by kntroh** [comment]
I sent pull request #50.

**Comment by jacob-carlborg** [comment]
In the future, if you prefix the commit message with `Fix #49` GitHub will automatically close the issue when the PR is merged.

**Comment by kntroh** [comment]
I'ill use it from next. Thanks.
