### ISSUE TITLE
link error with linux libs in latest dwt/dub test

### ISSUE THREAD

**Issue by MartinNowak** [d-widget-toolkit/dwt#78]
Looks like something [broke recently](https://buildkite.com/dlang/dub/builds/1489#3de77741-8946-4d77-a6e6-f442af19e491/105-121), was still OK with [dub stable](https://buildkite.com/dlang/dub/builds/1488#f690c4b3-2f85-4756-8b11-1a80c68a159a) so I'd assume it could be some recent changes to the dub.sdl or so.

**Comment by Geod24** [comment]
Fixed by https://github.com/dlang/ci/pull/441, I re-triggered the pipeline and this time it should pass.
