### ISSUE TITLE
[QUESTION] I have a couple of questions to make

### ISSUE THREAD

**Issue by Godnyx** [d-widget-toolkit/dwt#93]
Hey man! I would like to make you some questions if you have some time and you don't mind. But before I would like to thank you a lot for keeping DWT active. It's really impressive and I really like a lot the idea of having a native D gui library as from what I know, DWT is the only one that's active right now!

Now my questions are about the project? Do you plan on supporting it in the future? Do you use it in your personal work? I know that everything can change in the future and no one can promise something but at least how you see things now? I would like to know because I'm new to D and I would like to probably help with the project If you want to continue and support it and there are plans. So yeah if you have some time and you want to discuss about it, I would really appreciate it. But if not, I wish you the best my friend!

**Comment by jacob-carlborg** [comment]
> But before I would like to thank you a lot for keeping DWT active. It's really impressive and I really like a lot the idea of having a native D gui library as from what I know, DWT is the only one that's active right now!

Thanks!

> Do you plan on supporting it in the future? Do you use it in your personal work? I know that everything can change in the future and no one can promise something but at least how you see things now? I would like to know because I'm new to D and I would like to probably help with the project If you want to continue and support it and there are plans. So yeah if you have some time and you want to discuss about it, I would really appreciate it. But if not, I wish you the best my friend!

The current plan is that I'm not doing much active coding work. I'm more or less just making sure it works with the latest compilers. Unfortunately I'm not using it for any of my own projects, that's a reason why it's not very active. DWT currently only works on Linux and Windows but my main platform is macOS. That's the main reason I'm not currently using it. Several years ago I worked on porting it to macOS, it's available in a separate repository [1]. It's really old, it was started back in the D1 days, so it's still written in D1. If you're not aware, DWT is a port of SWT [2] from Java to D. It's very tedious and quite boring now to port the code manually. I also don't have much spare time available. I did start working on a tool [3] that allows to automatically translate Java code to D with the indention that SWT for macOS could be ported to D and newer versions could of SWT could be ported as well.

With that said, I'm happy to accept contributes and I will review and merge pull requests. Recently summer-alice has started contributing by updating DWT to a later version of SWT [4], so now there's some new activity.

You can have a look here in the D forums for discussions on the same topic [5].

BTW, I just enabled the Discussion feature for this repository for any future questions and discussions [6].

[1] https://github.com/d-widget-toolkit/dwt-mac
[2] https://www.eclipse.org/swt/
[3] https://github.com/d-widget-toolkit/jport
[4] https://github.com/d-widget-toolkit/dwt/pulls?q=is%3Apr+
[5] https://forum.dlang.org/thread/lebaxqmdfrsqgmilcdpt@forum.dlang.org
[6] https://github.com/d-widget-toolkit/dwt/discussions/94

**Comment by Godnyx** [comment]
You are awesome! I'll make sure to help with the tool then so we can automatically port it then! Have an amazing day in whatever you do bro!

**Comment by jacob-carlborg** [comment]
Thanks, you too.
