### ISSUE TITLE
Tabs of CTabFolder are not drawn at Windows

### ISSUE THREAD

**Issue by kntroh** [d-widget-toolkit/dwt#98]
I have confirmed this problem with snippet165.
The cause seems to be in 7581565f775c23dd68dbe2b3c31946bbe75f788c. But the changes are significant, so it will take some time to find out.

**Comment by kntroh** [comment]
#92 made me understand the circumstances (sorry I panicked). I think, CTabFolder is currently in a non-working state, so it's better to work on it in a separate branch.

**Comment by summer-alice** [comment]
> #92 made me understand the circumstances (sorry I panicked).

Sorry, my bad. I can confirm that this doesn't work with Gtk either. I am planning on finishing it, but to do so requires other classes to be added/updated (e.g. it uses a new class called `DPIUtil`, which in turn requires the `Drawable` interface to have the `isAutoscalable` method (#97)). The `CTabFolderRenderer` port needs to be finished as well.

> I think, CTabFolder is currently in a non-working state, so it's better to work on it in a separate branch.

I'd be happy to do that, but since I can't create branches on this repository I'm limited to pull requests, which @jacob-carlborg (understandably) prefers to be smaller.

**Comment by kntroh** [comment]
Up until now, updates to the DWT have been limited to small changes to fix bugs or upgrade the dlang. For this kind of update, I think it would be easy to merge it into the master branch while also merging it into 4.7 (or something). That way, when the 4.7 work is done, we can merge it back into master and there will be no conflict.
In the meantime, I think it is best to avoid a situation where master does not work.

**Comment by jacob-carlborg** [comment]
> I think it would be easy to merge it into the master branch while also merging it into 4.7 (or something)

My merging to both master and 4.7? Wouldn't that defeat the purpose of having a separate branch?

**Comment by kntroh** [comment]
What I mean is to create two branches, one for 4.7 and one for master, and then merge into both master and 4.7 when small changes such as bug fixes occur.
If there are no other major changes, this should work fine.

**Comment by kntroh** [comment]
In this case, I think master would be branched from just before 7581565.

**Comment by jacob-carlborg** [comment]
Yes, the master branch would need to be merged into the 4.7 from time to time to keep it up to date.

**Comment by kntroh** [comment]
I'll explain my thinking.

 1. Create two main lines, one for the 4.7 and one for the master.
 2. A updates for SWT 4.7 will be merged into the 4.7 only.
 3. All other (small) changes will be merged into both the 4.7 and the master.

If we keep this way, we should be able to eventually merge the 4.7 into the master without any problems.
The flow will be as follows:

```
master ---o-----------o--------o------------------o---------o-----------o-----
           \           \      /                    \       /           /
            \   bug fix o----o   udpate for new dmd o-----o           /
             \                \                            \         /
         4.7  o---o---------o--o---o-----------------o------o-------o
                   \       /        \               /
                    o-----o          o-------------o
                        updates for SWT 4.7
```

**Comment by jacob-carlborg** [comment]
Yeah, that's more or less that I'm saying.

**Comment by jacob-carlborg** [comment]
I've created a new branch now: [4.7](https://github.com/d-widget-toolkit/dwt/tree/4.7).

**Comment by kntroh** [comment]
Thanks. however, the master branch needs to be rolled back to 12923287a0ee559f78230ffb98f823146018cc54.
@summer-alice From now on, you can send a pull request to 4.7.

**Comment by jacob-carlborg** [comment]
@summer-alice is it fine to rollback to https://github.com/d-widget-toolkit/dwt/commit/12923287a0ee559f78230ffb98f823146018cc54? You would need to redo those pull requests (#91 and #96) and target the 4.7 branch instead.

**Comment by summer-alice** [comment]
> @summer-alice is it fine to rollback to [1292328](https://github.com/d-widget-toolkit/dwt/commit/12923287a0ee559f78230ffb98f823146018cc54)?

Unless I'm missing something, I'm not sure that is the right commit to be rolling back to. Running the snippet on my computer with commit 1292328 as the `HEAD` doesn't fix this issue. For this snippet to work properly on Gtk requires going back to at least 9395c81, which is the commit before I started updating the `CTabFolder` class.

>  You would need to redo those pull requests (#91 and #96) and target the 4.7 branch instead.

No worries about re-sending pull requests, but wouldn't #91 also be okay for the `master` branch? It fixes a compile-time bug and updates the CI. The code the commit shows I added in the `Display` class is the same for both SWT 3.4.2 and 4.7.3.

**Comment by jacob-carlborg** [comment]
> No worries about re-sending pull requests, but wouldn't #91 also be okay for the master branch? It fixes a compile-time bug and updates the CI. The code the commit shows I added in the Display class is the same for both SWT 3.4.2 and 4.7.3.

I just looked at which PRs were between 1292328 and master. I didn't look that carefully what they did now.

**Comment by summer-alice** [comment]
> > No worries about re-sending pull requests, but wouldn't #91 also be okay for the master branch? It fixes a compile-time bug and updates the CI. [...]
> 
> I just looked at which PRs were between [1292328](https://github.com/d-widget-toolkit/dwt/commit/12923287a0ee559f78230ffb98f823146018cc54) and master. I didn't look that carefully what they did now.

That's fine. #91 is the only bug fix, the rest are updating things to 4.7.3 or rearranging code.

**Comment by jacob-carlborg** [comment]
Do we have an agreement on how far we need to rollback?

**Comment by kntroh** [comment]
Sorry, 1292328 was my mistake idea, we need to rollback all CTabFolder relationships. If we want to be precise, it would be b54c611, but 9395c81 is practically fine.
I couldn't check to see if there are any other widgets in the halfway state (it seems unlikely). I'll let @summer-alice decide.

**Comment by summer-alice** [comment]
> Sorry, [1292328](https://github.com/d-widget-toolkit/dwt/commit/12923287a0ee559f78230ffb98f823146018cc54) was my mistake idea, we need to rollback all CTabFolder relationships. If we want to be precise, it would be [b54c611](https://github.com/d-widget-toolkit/dwt/commit/b54c61199c14d282645ca0934c7e7fa72a4274f6), but [9395c81](https://github.com/d-widget-toolkit/dwt/commit/9395c81c7866cecc234d245235dc478a2bbe065d) is practically fine.
> I couldn't check to see if there are any other widgets in the halfway state (it seems unlikely). I'll let @summer-alice decide.

To avoid any of ports which are in a "halfway state", we'll want to rollback to b54c611. The `CTabFolderRenderer` class wasn't finished due to it depending on some other custom widgets needing an update (they all seem to depend on each other...).

In other words, let's rollback to b54c611.

**Comment by kntroh** [comment]
#99 merging solved the problem.
@jacob-carlborg @summer-alice Thanks!
